install:
	mkdir -p /usr/sbin/spack
	install -c forge/forge.sh /usr/sbin/forge
	install -c wield/wield.sh /usr/sbin/wield
	install -c spack/spack.sh /usr/sbin/spack
	install -c libspack.sh    /etc/spack.conf

