install:
	mkdir -p /usr/lib/spack
	install -c forge/forge.sh /usr/bin/forge
	install -c wield/wield.sh /usr/bin/wield
	install -c spack/spack.sh /usr/bin/spack
	install -c libspack.sh    /usr/lib/spack/libspack

